# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 南柯的技术专栏
brief-intro: Android and HTML Coder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crazymen-nanke.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username: crazymen-nanke
email: 2395353168@QQ.com
weibo_username: #
zhihu_username: #
linkedIn_username: #
dribbble_username: #

description_footer: 本站记录我IT之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
#disqus_shortname: Svip_NanKe


# 评论系统
# Gitalk 
<!-- Link Gitalk 的支持文件  -->

  
		clientID: 'fa8361f5fa969e6aa262',
		clientSecret: '4f721a2dc12a6eae3f7c374b7d695c0d6d2ef405',
		repo: 'crazymen-nanke.io',
		owner: 'crazymen-nanke',
		admin: ['crazymen-nanke'],
		// facebook-like distraction free mode
		distractionFreeMode: false
	



# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: dbf5b8f14b2f79bcc948655a6bca7062
google_analytics_id: #UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
